tap "homebrew/cask"
tap "homebrew/cask-drivers"

# Shell
brew "zsh"
brew "zsh-completions"
cask "iterm2"

# Development
cask "dotnet-sdk"
brew "git"
cask "visual-studio-code"
cask "docker"
cask "rider"
cask "microsoft-azure-storage-explorer"

# Applications
cask "slack"
cask "microsoft-edge"
cask "gpg-suite-no-mail"
cask "gimp"
cask "microsoft-excel"
cask "microsoft-word"
cask "onedrive"
cask "todoist"
cask "messenger"
cask "parallels"
cask "parallels-toolbox"
cask "pdf-expert"
cask "postman"
cask "microsoft-teams"
cask "remarkable"
cask "teamviewer"
cask "elgato-stream-deck"
cask "elgato-control-center"
cask "microsoft-remote-desktop"